spring:
    application:
        name: pre-process-openrewriteutility
git:
    branch:
        name:
            openrewrite:
                recipe:
                    name:
                        sync: java18
    process:
        available: checkout|push
        available.active: push
        available.push.comments: code push through auto-process
    repo:
        path: C:\Git\checkout2\
logging:
    file:
        name: process.log
    pattern:
        file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} [%level] %c{1.} [%t] %m%n'
